version: '2'
services:
  centos7:
    build: docker/centos7/
    privileged: true
    entrypoint: /usr/lib/systemd/systemd
    ports:
      - "3000:3000"
      - "80:80"
  jessie64:
    build: docker/jessie64/
    privileged: true
    entrypoint: /lib/systemd/systemd
    ports:
      - "3000:3000"
      - "80:80"
  xenial64:
    build: docker/xenial64/
    privileged: true
    entrypoint: /sbin/init
    ports:
      - "3000:3000"
      - "9090:9090"
      - "80:80"
